//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cetys.APIs.Escolar.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumnoPrograma
    {
        public int idAlumnoPrograma { get; set; }
        public string matricula { get; set; }
        public string idPrograma { get; set; }
        public Nullable<int> semestre { get; set; }
        public Nullable<double> avance { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual programa programa { get; set; }
    }
}
