//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cetys.APIs.Escolar.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumnoPrograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alumnoPrograma()
        {
            this.alumno = new HashSet<alumno>();
            this.programa1 = new HashSet<programa>();
        }
    
        public int idAlumnoPrograma { get; set; }
        public string matricula { get; set; }
        public Nullable<int> idPrograma { get; set; }
        public Nullable<int> semestre { get; set; }
        public Nullable<double> avance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumno> alumno { get; set; }
        public virtual alumno alumno1 { get; set; }
        public virtual programa programa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<programa> programa1 { get; set; }
    }
}
