//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cetys.APIs.Escolar.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumnoMateria
    {
        public int idAlumnoMateria { get; set; }
        public string matricula { get; set; }
        public string idMateria { get; set; }
        public Nullable<bool> aprobada { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual materia materia { get; set; }
    }
}
