//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cetys.APIs.Escolar.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class maestroMateria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maestroMateria()
        {
            this.maestro1 = new HashSet<maestro>();
            this.materia1 = new HashSet<materia>();
        }
    
        public int idMaestroMateria { get; set; }
        public Nullable<int> numEmpleado { get; set; }
        public Nullable<int> idMateria { get; set; }
    
        public virtual maestro maestro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maestro> maestro1 { get; set; }
        public virtual materia materia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materia> materia1 { get; set; }
    }
}
