//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cetys.APIs.Escolar.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class maestroMateria
    {
        public int idMaestroMateria { get; set; }
        public Nullable<int> numEmpleado { get; set; }
        public string idMateria { get; set; }
    
        public virtual maestro maestro { get; set; }
        public virtual materia materia { get; set; }
    }
}
