//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cetys.APIs.Escolar.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materia()
        {
            this.maestroMateria = new HashSet<maestroMateria>();
            this.materiaPrograma1 = new HashSet<materiaPrograma>();
        }
    
        public int idMateria { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idMaestroMateria { get; set; }
        public Nullable<int> idMateriaPrograma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maestroMateria> maestroMateria { get; set; }
        public virtual maestroMateria maestroMateria1 { get; set; }
        public virtual materiaPrograma materiaPrograma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materiaPrograma> materiaPrograma1 { get; set; }
    }
}
