//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cetys.APIs.Escolar.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EscolarEquipo5Entities : DbContext
    {
        public EscolarEquipo5Entities()
            : base("name=EscolarEquipo5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<alumnoPrograma> alumnoPrograma { get; set; }
        public virtual DbSet<campus> campus { get; set; }
        public virtual DbSet<maestro> maestro { get; set; }
        public virtual DbSet<maestroMateria> maestroMateria { get; set; }
        public virtual DbSet<materia> materia { get; set; }
        public virtual DbSet<materiaPrograma> materiaPrograma { get; set; }
        public virtual DbSet<programa> programa { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
